# Generated by Django 5.2.8 on 2025-11-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emmployer',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(default='emp@org.com', max_length=100)),
                ('emp_mob', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
